/* eslint-disable prettier/prettier */
export default [
  {
    url: "https://www.claesadvocaten.be/",
    name: "Claes Advocaten",
    headsponsor: "YES",
    order: "2",
    type: "CLUBSPONSOR",
    cloudinaryID: "claes-advocaten",
  },
  {
    url: "http://www.dakwerken-vanelshocht.be",
    name: "Van Elshocht bvba",
    headsponsor: "YES",
    order: "4",
    type: "CLUBSPONSOR",
    cloudinaryID: "dakwerken-van-elshocht",
  },
  {
    url: "http://www.tventiel.be/",
    name: "t Ventiel",
    headsponsor: "NO",
    order: "11",
    type: "CLUBSPONSOR",
    cloudinaryID: "t-ventiel",
  },
  {
    url: "http://www.reizenboone.be",
    name: "Reizen Boone",
    headsponsor: "NO",
    order: "13",
    type: "CLUBSPONSOR",
    cloudinaryID: "reizen-boone",
  },
  {
    url: "http://www.klare-wijn.be/",
    name: "Klare Wijn",
    headsponsor: "NO",
    order: "17",
    type: "CLUBSPONSOR",
    cloudinaryID: "klare-wijn",
  },
  {
    url:
      "https://www.crelan.be/nl/particulieren/kantoor/kantoor-jan-van-den-wijngaert",
    name: "Crelan - Kantoor Jan Van den Wijngaert",
    headsponsor: "NO",
    order: "23",
    type: "CLUBSPONSOR",
    cloudinaryID: "crelan_e4wiot",
  },
  {
    url: "http://www.gebroedersnijs.be",
    name: "Nijs Gebr BVBA",
    headsponsor: "NO",
    order: "26",
    type: "CLUBSPONSOR",
    cloudinaryID: "gebroeders-nijs",
  },
  {
    url: "http://garage.peugeot.be/selleslaghs",
    name: "Garage Selleslaghs NV",
    headsponsor: "NO",
    order: "33",
    type: "CLUBSPONSOR",
    cloudinaryID: "peugeot",
  },
  {
    url: "http://www.shoepoint.be/",
    name: "Shoepoint",
    headsponsor: "NO",
    order: "34",
    type: "CLUBSPONSOR",
    cloudinaryID: "shoepoint",
  },
  {
    url: "http://www.tuinhoutcentrum.be/",
    name: "Tuinhoutcentrum Kontich",
    headsponsor: "YES",
    order: "1",
    type: "CLUBSPONSOR",
    cloudinaryID: "tuinhoutcentrum",
  },
  {
    url: "http://www.vdwfinance.be",
    name: "VDW Finance",
    headsponsor: "NO",
    order: "38",
    type: "CLUBSPONSOR",
    cloudinaryID: "van-den-wijngaert",
  },
  {
    url: "http://www.groepvanhaute.be/",
    name: "Groep Van Haute N.V",
    headsponsor: "NO",
    order: "41",
    type: "CLUBSPONSOR",
    cloudinaryID: "van-haute-bvba",
  },
  {
    url: "http://www.jakosportshop.be/",
    name: "JAKO",
    headsponsor: "YES",
    order: "9",
    type: "CLUBSPONSOR",
    cloudinaryID: "jako",
  },
  {
    url: "http://www.nicksport.be",
    name: "Nick Sport",
    headsponsor: "YES",
    order: "9",
    type: "CLUBSPONSOR",
    cloudinaryID: "nick-sport",
  },
  {
    url: "http://www.traqo.be/",
    name: "Traqo BVBA",
    headsponsor: "NO",
    order: "20",
    type: "CLUBSPONSOR",
    cloudinaryID: "traqo",
  },
  {
    url: "http://www.klimaplan.be",
    name: "Klimaplan",
    headsponsor: "YES",
    order: "9",
    type: "CLUBSPONSOR",
    cloudinaryID: "klimaplan",
  },
  {
    url: "http://www.gilberte.be/",
    name: "Wasserij Gilberte",
    headsponsor: "NO",
    order: "7",
    type: "DAMESSPONSOR",
    cloudinaryID: "wasserij-gilberte_m0ytr6",
  },
  {
    url: "http://ulp.be/",
    name: "ULP",
    headsponsor: "YES",
    order: "1",
    type: "DAMESSPONSOR",
    cloudinaryID: "ulp",
  },
  {
    url: "http://www.cronos.be/",
    name: "CRONOS",
    headsponsor: "YES",
    order: "2",
    type: "CLUBSPONSOR",
    cloudinaryID: "cronos",
  },
  {
    url: "http://www.vandenbergh.co/",
    name: "Van den Bergh",
    headsponsor: "NO",
    order: "7",
    type: "CLUBSPONSOR",
    cloudinaryID: "van-den-bergh",
  },
  {
    url: "http://www.gozar.be/pages/Gozar.aspx",
    name: "Gozar",
    headsponsor: "NO",
    order: "7",
    type: "CLUBSPONSOR",
    cloudinaryID: "gozar",
  },
  {
    url: "http://www.depotnoord.be/",
    name: "Depot Noord",
    headsponsor: "NO",
    order: "6",
    type: "DAMESSPONSOR",
    cloudinaryID: "depot-noord",
  },
  {
    url: "http://www.apotheekvranken.be/",
    name: "Apotheek Vranken",
    headsponsor: "NO",
    order: "10",
    type: "CLUBSPONSOR",
    cloudinaryID: "apotheek-vranken",
  },
  {
    url: "http://dcm-info.com/",
    name: "DCM",
    headsponsor: "NO",
    order: "12",
    type: "CLUBSPONSOR",
    cloudinaryID: "dcm",
  },
  {
    name: "DC4GROUP",
    headsponsor: "NO",
    order: "15",
    type: "DAMESSPONSOR",
    cloudinaryID: "dc4-group",
  },
  {
    url: "http://swaab.portas.be/",
    name: "Portas",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "portas",
  },
  {
    url: "http://www.carrosseriewaumans.be/",
    name: "Carrosserie Waumans",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "carrosserie-waumans",
  },
  {
    url: "",
    name: "T&S Tuinen",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "ts-tim-demaere",
  },
  {
    url: "http://www.springkasteelantwerpen.be/",
    name: "Springkasteel Antwerpen",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "springkasteel-antwerpen",
  },
  {
    url: "https://www.facebook.com/cafechapo/",
    name: "Café Chapo",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "cafe-chapo",
  },
  {
    url: "http://www.bazarkekonkaz.be/",
    name: "Bazarke",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "het-bazarke",
  },
  {
    url: "http://www.boekjesenzo.be/",
    name: "Dagbladhandel boekjes en zo",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "boekjes-en-zo",
  },
  {
    url: "",
    name: "Party Ride",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "party-ride",
  },
  {
    url: "http://www.jmwprinting.be/",
    name: "JMW Printing",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "jmw-printing",
  },
  {
    url: "http://www.gilberte.be/",
    name: "Wasserij Gilberte",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "wasserij-gilberte",
  },
  {
    url: "http://www.goudengids.be/de-zwaluw-kontich-2550/",
    name: "Café De Zwaluw",
    headsponsor: "NO",
    order: "10",
    type: "CLUBSPONSOR",
  },
  {
    url: "http://www.goudengids.be/het-belegde-broodje-kontich-2550/",
    name: "Het Belegde Broodje",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "belegde-broodje",
  },
  {
    url: "http://www.lunchgarden.com/nl/restaurant/edegem",
    name: "Lunch Garden",
    headsponsor: "YES",
    order: "1",
    type: "CLUBSPONSOR",
    cloudinaryID: "lunch-garden-edegem",
  },
  {
    url: "http://www.verheyenbinnenhuisinrichting.be/",
    name: "Verheyen Binnenhuisinrichting",
    headsponsor: "NO",
    order: "10",
    type: "CLUBSPONSOR",
    cloudinaryID: "verheyen",
  },
  {
    url: "http://www.tcict.be/",
    name: "TCict Computer Systems",
    headsponsor: "NO",
    order: "0",
    type: "KANTINESPONSOR",
    cloudinaryID: "tcict",
  },
  {
    url: "https://www.sportveldbelijning.be/",
    name: "Footline",
    headsponsor: "YES",
    order: "10",
    type: "CLUBSPONSOR",
    cloudinaryID: "footline",
  },
  {
    url: "http://www.babypaleis.be/",
    name: "Babypaleis",
    headsponsor: "NO",
    order: "10",
    type: "DAMESSPONSOR",
    cloudinaryID: "kinderdagverblijf-babypaleis",
  },
  {
    url: "https://www.beobank.be/nl/particulier/pos/beobank-lint",
    name: "Beobank Vingerhoets",
    headsponsor: "YES",
    order: "5",
    type: "CLUBSPONSOR",
    cloudinaryID: "beobank",
  },
  {
    url: "https://www.transfert.be/",
    name: "Transfert",
    headsponsor: "YES",
    order: "5",
    type: "CLUBSPONSOR",
    cloudinaryID: "transfert",
  },
  {
    url: "http://www.copycenterkontich.be/",
    name: "Copycenter Kontich",
    headsponsor: "NO",
    order: "5",
    type: "KANTINESPONSOR",
    cloudinaryID: "copycenter",
  },
  {
    url: "https://boonenzonwering.be/",
    name: "Zonwering Boonen",
    headsponsor: "YES",
    order: "5",
    type: "CLUBSPONSOR",
    cloudinaryID: "Screenshot_2021-12-03_at_20.56.41_gcpaqt",
  },
  {
    url: "https://partner.volvocars.be/nl/vermant",
    name: "Volvo Vermant",
    headsponsor: "YES",
    order: "2",
    type: "CLUBSPONSOR",
    cloudinaryID: "volvo-vermant",
  },
  {
    url: "https://kiavermant.be/",
    name: "Kia Vermant",
    headsponsor: "YES",
    order: "2",
    type: "CLUBSPONSOR",
    cloudinaryID: "KIA-vermant-zilver-blok_xxy8kw",
  },
  {
    url: "https://www.aquarius.be/nl",
    name: "Aquarius",
    headsponsor: "NO",
    order: "5",
    type: "CLUBSPONSOR",
    cloudinaryID: "aquarius",
  },
  {
    url: "https://www.tenhove.be/",
    name: "Fiduciaire Ten Hove ",
    headsponsor: "NO",
    order: "5",
    type: "DAMESSPONSOR",
    cloudinaryID: "ten-hove",
  },
  {
    url: "http://www.stijnbevers.be/",
    name: "Stijn Bevers",
    headsponsor: "YES",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "stijn-bevers",
  },
  {
    url: "https://www.straalstudio.be/",
    name: "Straalstudio",
    headsponsor: "YES",
    order: "8",
    type: "DAMESSPONSOR",
    cloudinaryID: "straalstudio",
  },
  {
    url: "https://www.schilderstudio.be/",
    name: "BJ invest",
    headsponsor: "YES",
    order: "8",
    type: "DAMESSPONSOR",
    cloudinaryID: "logo-schilderstudio-schilder-schilderwerken_v0pujr",
  },
  {
    url: "https://www.velodi.be/",
    name: "Fietsenwinkel Velodi",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "velodi_tjhaw9",
  },
  {
    url: "https://www.facebook.com/GOSTOwijnproeverij/",
    name: "Wijnbar Gosto",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "gosto_y7fqnd",
  },
  {
    url: "http://www.deganzenpoel.be/",
    name: "De Ganzenpoel",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "ganzenpoel_l7vtcw",
  },
  {
    url: "http://www.vinotilus.be/nl",
    name: "Vinotilus",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_vinotilus_transparant_mbcwgd",
  },
  {
    url: "https://forumadvocaten.be/",
    name: "Forum Advocaten",
    headsponsor: "YES",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "forum_advocaten",
  },
  {
    url: "https://www.disprimo.be/",
    name: "Disprimo IT",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "disprimo_kjhwcf",
  },
  {
    url: "https://www.premio.be/vestigingen/premio-vr-kontich/",
    name: "Premio VR Kontich",
    headsponsor: "YES",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "vr_profile_kontich", // logo aanpassen
    highlight: false,
  },
  {
    url: "https://www.argenta.be/nl/kantoren/vukon-bvba-3635.html",
    name: "Argenta Kontich",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "website_m77xsf",
    highlight: false,
  },
  {
    url: "http://www.dirkbroes.be/familieberichten.html",
    name: "Dirk Broes Uitvaartverzorging",
    headsponsor: "YES",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "1a02813962b6c_mg1yx9",
    highlight: false,
  },
  {
    url: "https://www.elmos.be/nl",
    name: "Elmos",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "elmos_zirwol",
    highlight: false,
  },
  {
    url: "http://www.garageverlinden.be/",
    name: "Verlinden Duffel",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Logo_Verlinden_Renault_wxjypm",
    highlight: false,
  },
  {
    url: "https://www.volkswelvaart.be/",
    name: "Volkswelvaart",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_volkswelvaart_website_xigz3y",
    highlight: false,
  },
  {
    url: "https://www.ing.be/nl/retail",
    name: "ING Hove-Kontich",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "16x12_Logos_Partners_ING_fqpsof",
    highlight: false,
  },
  {
    url: "https://www.trentimmo.be/",
    name: "Trent Immo",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "368849323_trent_immo_logo_egehym",
    highlight: false,
  },
  {
    url: "http://qualitychape.be/",
    name: "Quality Chape",
    headsponsor: "YES",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Reclamebord_FC_Kontich_zx4zrf",
    highlight: false,
  },
  {
    url: "http://www.vastgoedplus.be/",
    name: "Vastgoed Plus",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_dmidm2",
    highlight: false,
  },
  {
    url: "https://www.brico.be/nl/storedetail/3446/kontich",
    name: "Brico",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Screenshot_2021-10-16_at_16.43.39_rxlicp",
    highlight: false,
  },
  {
    url: "https://www.autonatiegroup.be/",
    name: "autonatie groep",
    headsponsor: "NO",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "unnamed_2_kcccnh",
    highlight: false,
  },
  {
    url: "https://www.procondi.com/",
    name: "Procondi",
    headsponsor: "YES",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "unnamed_1_vt2jdi",
    highlight: false,
  },
  {
    url: "https://www.bjornies.be/",
    name: "Bjornies Ijs",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Logo_Bjornies_1_kk0uub",
    highlight: false,
  },
  {
    url: "https://fietsenjacobs.be/",
    name: "Fietsen Jacobs",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "fietsen_jacobs_ssjskz",
    highlight: false,
  },
  {
    url: "https://thiebautclaesadvocaten.be/",
    name: "Thiebaut Claes advocaten",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Logo_02_psybe4",
    highlight: false,
  },
  {
    url: "http://www.denjoe-renovaties.be/",
    name: "DEN JOE RENOVATIES",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_nxvw0h",
    highlight: false,
  },
  {
    url: "https://www.u-properties.be/",
    name: "U-Properties",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Screenshot_2023-03-22_at_19.42.51_at3now",
    highlight: false,
  },
  {
    url: "http://www.jarent.be/",
    name: "JA rent",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_nxjmyc",
    highlight: false,
  },
  {
    url: "https://www.quick.be/nl/restaurant/kontich",
    name: "Quick",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "quick-2-logo-png-transparent_nv1mkx",
    highlight: false,
  },
  {
    url: "https://www.facebook.com/eendrachtkontich/",
    name: "Cafe Den Eendracht",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Screenshot_2023-09-01_at_21.05.27_yyngzc",
    highlight: false,
  },
  {
    url:
      "https://www.facebook.com/p/Rhila-100070347703275/?paipv=0&eav=AfZNnZqANBWqDuYIHphvoU8af-2fdtwiCNeuNW-7KNLFjCWDCLaWiD50jXqjAaM8GNg&_rdr",
    name: "Dakwerken Rhila",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_r5brim",
    highlight: false,
  },
  {
    url: "https://bjcelektro.be/",
    name: "BJC",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_nxjmyc",
    highlight: false,
  },
  {
    url: "https://www.ecohome.be/",
    name: "Ecohome",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "plakaat-ecohome_page-0001_zpct2c",
    highlight: false,
  },
  {
    url: "https://www.companyweb.be/nl/0404020242/galvani",
    name: "Galvani",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo-1_h8lwxs",
    highlight: false,
  },
  {
    url: "https://www.liptonicetea.be/nl/home.html",
    name: "Lipton Ice Tea",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Logo_Lipton_Ice_Tea_lxenhd",
    highlight: false,
  },
  {
    url: "https://ab-inbev.be/",
    name: "Inbev",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "AB-Inbev-logo_1_qbtbvb",
    highlight: false,
  },
  {
    url: "https://nl.coca-cola.be/",
    name: "Coca Cola",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Logo_Cola_xeepjr",
    highlight: false,
  },
  {
    url: "https://jdm.be/",
    name: "JDM Publicity",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logoTrans2_llptr4",
    highlight: false,
  },
  {
    url: "https://voldersbieren.be/",
    name: "Volders Bieren",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Logo_Volders_Bieren_dbkdll",
    highlight: false,
  },
  {
    url: "https://www.equans.be/nl",
    name: "Equans",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_1_kikzch",
    highlight: false,
  },
  {
    url: "https://www.cralux.be/",
    name: "Cralux",
    headsponsor: "yes",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo_transparant_zvrzsc",
    highlight: false,
  },
  {
    url: "https://www.iscstechnical.com/",
    name: "ISCS",
    headsponsor: "yes",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "637fa3f0955d31fb8d044e0e_iscs-logo_uckhvk",
    highlight: false,
  },
  {
    url:
      "https://www.facebook.com/p/Frituur-Miranda-100056290488960/?locale=nl_NL",
    name: "Frituur Miranda",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "Logo_Miranda_hbjkig",
    highlight: false,
  },
  {
    url: "https://www.facebook.com/p/Ronnyt-Kapperke-100083049451157/",
    name: "Ronny ‘t Kapperke",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "461296880_519123384199306_3144184702198729020_n_x1jsfi",
    highlight: false,
  },
  {
    url: "https://www.maesjenzoon.be/mjz-heating",
    name: "MJZ Heating",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "mjz_auqcjz",
    highlight: false,
  },
  {
    url: "https://bsdehelpendehand.be/",
    name: "De Helpende Hand",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "logo-dhh_ants91",
    highlight: false,
  },
  {
    url: "https://vandeweyerp.be/",
    name: "Int. Schrijnwerkerij Kris Van De Weyer",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "463012173_3829768693964817_4249613667277144282_n_zmjaa1",
    highlight: false,
  },
  {
    url:
      "https://www.google.com/search?q=Yannick+Neirynck+kontich&sca_esv=a602e8e6c3755c23&rlz=1C5CHFA_enBE1064BE1064&sxsrf=ADLYWIINzbZ0UPTP4WK1LBRyr1f1I0J6mA%3A1732656658726&ei=Ej5GZ7PwK7iJkdUPnKmiCA&ved=0ahUKEwizwaSF-fqJAxW4RKQEHZyUCAEQ4dUDCA8&uact=5&oq=Yannick+Neirynck+kontich&gs_lp=Egxnd3Mtd2l6LXNlcnAiGFlhbm5pY2sgTmVpcnluY2sga29udGljaEibCFDZBFjZBHACeACQAQCYAVWgAZoBqgEBMrgBA8gBAPgBAZgCAKACAJgDAIgGAZIHAKAHoQE&sclient=gws-wiz-serp",
    name: "Yannick Neirynck",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "neirynck_incchg",
    highlight: false,
  },
  {
    url: "https://eventstars.be/",
    name: "Eventstars",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "eventstars_b1erx5",
    highlight: false,
  },
  {
    url: "https://www.gielis-veremans.be/",
    name: "Gielis Veremans begrafenissen",
    headsponsor: "no",
    order: "8",
    type: "CLUBSPONSOR",
    cloudinaryID: "318869389_961414698166334_4046970272445476376_n_jncu1q",
    highlight: false,
  },
];
